name: portfolio_app
description: "A new Flutter project."
publish_to: 'Rohit Portfolio'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  firebase_core: ^3.5.0
  firebase_storage: ^12.3.1
  flutter:
    sdk: flutter
  flutter_downloader: ^1.11.8
  flutter_svg: ^2.0.10+1
  http: ^1.2.2
  path_provider: ^2.1.4
  percent_indicator: ^4.2.3
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/svgIcons/
 
  
  fonts:
    - family: Console 
      fonts:
        - asset: assets/fonts/Inconsolata-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inconsolata-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inconsolata-Bold.ttf
          weight: 700
